# Copyright (c) 2019 Ant Financial
#
# SPDX-License-Identifier: Apache-2.0
#

sudo: required
dist: bionic

os:
    - linux

language: rust
rust:
    - nightly

env:
    - target_branch=$TRAVIS_BRANCH RUST_AGENT=yes

before_install:
    - ".ci/setup.sh"
    - ".ci/install_go.sh"
    - ".ci/install_rust.sh"
    - ".ci/static-checks.sh"

# need to install rust from scratch?
# still need go to download github.com/kata-containers/tests
# which is already installed?

install:
    - cd ${TRAVIS_BUILD_DIR} && make default

script:
    - cd ${TRAVIS_BUILD_DIR} && make check || true
    - ".ci/debug_scripts.sh"
